# Generated by Django 4.0.3 on 2022-05-30 20:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0002_alter_bebida_chico_alter_bebida_grande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comida',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatares'),
        ),
    ]
