# Generated by Django 4.0.3 on 2022-05-30 23:38

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0003_comida_description_comida_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comida',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 23, 38, 25, 242132, tzinfo=utc)),
        ),
    ]
