# Generated by Django 4.0.3 on 2022-04-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
