# Generated by Django 4.0.3 on 2022-05-30 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indice', '0004_userinfo_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='link',
        ),
    ]
