# Generated by Django 4.0.3 on 2022-05-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice', '0006_userinfo_descripcion_userinfo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
