# Generated by Django 4.0.3 on 2022-05-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice', '0007_alter_userinfo_descripcion_alter_userinfo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='descripcion',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='link',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
