# Generated by Django 4.0.3 on 2022-05-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indice', '0008_alter_userinfo_descripcion_alter_userinfo_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='imagen',
            new_name='avatar',
        ),
    ]
