# Generated by Django 4.0.3 on 2022-05-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indice', '0009_rename_imagen_userinfo_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='descripcion',
            new_name='more_description',
        ),
    ]
